-- Initialize ERP database schema based on DBF analysis
CREATE DATABASE IF NOT EXISTS sales_db;
USE sales_db;

-- Customers table (based on clientes.DBF)
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    numcli VARCHAR(5) UNIQUE NOT NULL,
    nomcli VARCHAR(200),
    calle VARCHAR(60),
    numext VARCHAR(10),
    colonia VARCHAR(40),
    ciudad VARCHAR(30),
    estado VARCHAR(20),
    cp VARCHAR(6),
    telefono VARCHAR(30),
    fax VARCHAR(20),
    clasif VARCHAR(5),
    ventano DECIMAL(12,2),
    ultvent DATE,
    atvent VARCHAR(40),
    atcobr VARCHAR(40),
    email1 VARCHAR(40),
    email2 VARCHAR(40),
    rfc VARCHAR(13),
    limcred DECIMAL(12,2),
    saldo DECIMAL(12,2),
    pjedesc DECIMAL(5,2),
    diascred INT,
    precioutil CHAR(1),
    recepfac VARCHAR(30),
    pagofac VARCHAR(30),
    obs TEXT,
    numcta VARCHAR(20),
    uid INT,
    numvend VARCHAR(5),
    obligareq BOOLEAN,
    suspendido BOOLEAN,
    direnvio TEXT,
    otrosdatos TEXT,
    impuesto1 DECIMAL(6,2),
    retencion1 DECIMAL(10,4),
    retencion2 DECIMAL(6,2),
    permitecod BOOLEAN,
    llavecred BOOLEAN,
    pais VARCHAR(15),
    clavecli VARCHAR(20),
    curp VARCHAR(20),
    nomcomer VARCHAR(40),
    cfgdatdoc TEXT,
    datosfe TEXT,
    statusweb INT,
    claveweb VARCHAR(32),
    numzona VARCHAR(5),
    metodopago TEXT,
    metodousar VARCHAR(2),
    numint VARCHAR(10),
    usocfdi VARCHAR(3),
    formapago VARCHAR(2),
    implocal TEXT,
    condpago VARCHAR(30),
    emailtw VARCHAR(50),
    numidtrib VARCHAR(40),
    idregimen VARCHAR(3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_numcli (numcli),
    INDEX idx_rfc (rfc),
    INDEX idx_ciudad (ciudad),
    INDEX idx_ultvent (ultvent)
);

-- Products table (based on arts.DBF)
CREATE TABLE IF NOT EXISTS products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    numart VARCHAR(20) UNIQUE NOT NULL,
    desc_product VARCHAR(60),
    codigo VARCHAR(20),
    unidad VARCHAR(5),
    unidefa VARCHAR(5),
    marca VARCHAR(30),
    modelo VARCHAR(30),
    linea VARCHAR(5),
    familia VARCHAR(5),
    categoria VARCHAR(5),
    numdep VARCHAR(11),
    valdep VARCHAR(9),
    ubica VARCHAR(10),
    series_control BOOLEAN,
    impuesto1 DECIMAL(5,2),
    impuesto2 DECIMAL(5,2),
    numprov VARCHAR(5),
    numprov1 VARCHAR(5),
    numprov2 VARCHAR(5),
    numprov3 VARCHAR(5),
    ultcomp DATE,
    ultcomp1 DATE,
    ultcomp2 DATE,
    ultcomp3 DATE,
    ultvent DATE,
    existencia DECIMAL(10,3),
    minimo DECIMAL(10,3),
    maximo DECIMAL(10,3),
    reorden DECIMAL(10,3),
    divisa CHAR(1),
    precio1 DECIMAL(13,2),
    precio2 DECIMAL(13,2),
    precio3 DECIMAL(13,2),
    precio4 DECIMAL(13,2),
    precio5 DECIMAL(13,2),
    factor1 DECIMAL(6,4),
    factor2 DECIMAL(6,4),
    factor3 DECIMAL(6,4),
    factor4 DECIMAL(6,4),
    factor5 DECIMAL(6,4),
    ultcosto DECIMAL(13,5),
    ultcosto1 DECIMAL(12,4),
    ultcosto2 DECIMAL(13,5),
    ultcosto3 DECIMAL(13,5),
    maxcosto DECIMAL(13,5),
    costoactua DECIMAL(13,5),
    costopro DECIMAL(13,5),
    ventano DECIMAL(12,2),
    ventanoqty DECIMAL(12,2),
    activo BOOLEAN,
    ultmaxcost DATE,
    ultactcost DATE,
    compano DECIMAL(12,2),
    companoqty DECIMAL(12,2),
    repyy BOOLEAN,
    cant_defa INT,
    excento BOOLEAN,
    preciopub DECIMAL(10,2),
    preciof BOOLEAN,
    servicio BOOLEAN,
    fechamod DATE,
    obs TEXT,
    usacaduc BOOLEAN,
    usalotes BOOLEAN,
    ventacorte DECIMAL(10,3),
    eskit BOOLEAN,
    uid INT,
    otrosdatos TEXT,
    pjedesc DECIMAL(6,2),
    oferta DECIMAL(12,4),
    insumo BOOLEAN,
    peso DECIMAL(10,3),
    largo DECIMAL(10,3),
    ancho DECIMAL(10,3),
    altura DECIMAL(10,3),
    cantxcj INT,
    foto VARCHAR(30),
    fotos TEXT,
    idmarca VARCHAR(5),
    preciov2 DECIMAL(12,5),
    preciov3 DECIMAL(12,5),
    preciov4 DECIMAL(12,5),
    preciov5 DECIMAL(12,5),
    ppubv2 DECIMAL(10,2),
    ppubv3 DECIMAL(10,2),
    ppubv4 DECIMAL(10,2),
    ppubv5 DECIMAL(10,2),
    vol2 DECIMAL(10,2),
    vol3 DECIMAL(10,2),
    vol4 DECIMAL(10,2),
    vol5 DECIMAL(10,2),
    statusweb INT,
    clavesat VARCHAR(8),
    implocal BOOLEAN,
    fracaranc VARCHAR(10),
    matpelig VARCHAR(5),
    embalaje VARCHAR(5),
    guiaid VARCHAR(30),
    guiaiddesc VARCHAR(60),
    esmatpelig BOOLEAN,
    factorv2 DECIMAL(6,4),
    factorv3 DECIMAL(6,4),
    factorv4 DECIMAL(6,4),
    factorv5 DECIMAL(6,4),
    fraccok BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_numart (numart),
    INDEX idx_codigo (codigo),
    INDEX idx_marca (marca),
    INDEX idx_familia (familia),
    INDEX idx_activo (activo),
    INDEX idx_ultvent (ultvent)
);

-- Movements/Transactions table (based on Movim.DBF)
CREATE TABLE IF NOT EXISTS movements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipodoc VARCHAR(2),
    numdoc VARCHAR(10),
    numpar VARCHAR(3),
    numart VARCHAR(20),
    precio DECIMAL(13,5),
    costo DECIMAL(13,5),
    costo2 DECIMAL(13,5),
    costopro DECIMAL(13,5),
    cant DECIMAL(10,3),
    pend DECIMAL(10,3),
    pendocant DECIMAL(10,3),
    empaque DECIMAL(10,3),
    devueltos DECIMAL(10,3),
    pjedesc DECIMAL(5,2),
    impuesto1 DECIMAL(5,2),
    impuesto2 DECIMAL(5,2),
    unidad VARCHAR(5),
    docant VARCHAR(15),
    obs TEXT,
    nseries TEXT,
    capaskit TEXT,
    pjedesc2 DECIMAL(6,2),
    pjedesc3 DECIMAL(6,2),
    pjedesc4 DECIMAL(6,2),
    lote VARCHAR(20),
    pjedesc1 DECIMAL(6,2),
    promoid INT,
    pendcanc DECIMAL(10,3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_tipodoc_numdoc (tipodoc, numdoc),
    INDEX idx_numart (numart),
    INDEX idx_docant (docant),
    INDEX idx_lote (lote),
    FOREIGN KEY (numart) REFERENCES products(numart) ON DELETE SET NULL
);

-- Table to track DBF file processing state
CREATE TABLE IF NOT EXISTS dbf_file_state (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file_path VARCHAR(500) NOT NULL UNIQUE,
    file_name VARCHAR(100) NOT NULL,
    last_modified TIMESTAMP,
    record_count INT DEFAULT 0,
    last_processed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    checksum_map JSON,
    processing_status ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR') DEFAULT 'PENDING',
    error_message TEXT,
    
    INDEX idx_file_name (file_name),
    INDEX idx_last_modified (last_modified),
    INDEX idx_processing_status (processing_status)
);

-- Table for tracking sync operations
CREATE TABLE IF NOT EXISTS sync_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    file_path VARCHAR(500),
    table_name VARCHAR(50),
    operation_type ENUM('INSERT', 'UPDATE', 'DELETE', 'BULK_LOAD') NOT NULL,
    record_count INT DEFAULT 0,
    records_processed INT DEFAULT 0,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration_ms INT,
    success BOOLEAN DEFAULT TRUE,
    error_message TEXT,
    
    INDEX idx_timestamp (timestamp),
    INDEX idx_file_path (file_path),
    INDEX idx_table_name (table_name),
    INDEX idx_operation_type (operation_type)
);